index.js
readme.md
src/install.js
src/update.js
test/integration-tests.js

This closes #4 
Lemme know what you think of the API @brianleroux @ryanblock

add support for hydrating specific subpaths

---

appveyor.yml
readme.md
src/install.js
src/update.js
test/integration-tests.js

also:
- manually list out paths for mock app.
- add tests for hydrating src/shared and src/views

⚙️➕ add appveyor (windows) builds via appveyor.yml

---

src/install.js

Should fix Windows issues

---

src/install.js

Fixes relative basepath lookup from incoming install request (jic)

---

package-lock.json
package.json
src/_printer.js
src/install.js
src/shared/copy-arc.js
src/shared/copy-shared.js
src/shared/copy-static-json.js
src/shared/copy-views.js
src/shared/index.js
src/update.js

Printer cleanup

---

src/install.js
src/update.js

Makes shared copying default, but enables opting out

---

src/install.js
src/shared/get-base-paths.js
src/update.js

Fixes issue where shared file copy destination paths may leak across Lambda executions

---

src/shared/copy-arc.js
src/shared/copy-shared.js
src/shared/copy-static-json.js
src/shared/copy-views.js

Adds only param to shared file hydration

---

src/install.js
src/update.js

Fix default param for basepath

---

changelog.md
src/shared/copy-arc.js
src/shared/copy-shared.js
src/shared/copy-static-json.js
src/shared/copy-views.js
src/shared/get-base-paths.js

Fixes issue with hydration of legacy runtimes

---

.github/workflows/build.yml
.npmignore

Update CI config and ignore files

---

changelog.md
package-lock.json
package.json
src/shared/copy-arc.js
src/shared/copy-shared.js
src/shared/copy-static-json.js
src/shared/copy-views.js
src/shared/get-base-paths.js

Runtimes fix

---

src/update.js
test/integration/integration-tests.js

 npm 7 compat

---

changelog.md
src/shared/copy.js

Fix weird shared file copier side effects caused by toggling symlinking on/off

---

changelog.md
src/install.js
src/update.js

Detect local vs global yarn installs

---

changelog.md
package.json
src/index.js

Installroot

---

changelog.md
src/shared/get-paths.js
test/integration/_shared.js
test/mocks/normal/_shared-custom/app.arc
test/mocks/normal/_shared-custom/app.arc-views
test/mocks/normal/_shared/app.arc-views
test/mocks/normal/app.arc
test/mocks/normal/src/myplugin/newlambda/index.js
test/mocks/normal/src/myplugin/newlambda/package.json
test/mocks/normal/src/plugins/myplugin.js

this fixes architect/architect#1116.

fixed bug where plugin-generated lambdas would not be hydrated with src/shared

---

changelog.md
src/shared/get-paths.js

Fix `views` not hydrating in projects that don't use `shared`, fixes #1133

---

changelog.md
src/actions/autoinstall/get-lambda-deps.js
src/actions/autoinstall/get-shared-deps.js
src/actions/autoinstall/index.js
test/unit/src/actions/autoinstall/get-lambda-deps-tests.js

Fix removing root dependencies during Lambda treeshaking

---

changelog.md
cli.js
index.js
package.json
readme.md
src/_printer.js
src/actions/install-update.js
src/index.js
src/shared/index.js
test/unit/index-tests.js
test/unit/src/_printer-tests.js

Remove legacy `hydrate()` interface; fixes #1168

---

changelog.md
src/_printer.js
src/shared/copy-shared.js
src/shared/copy-static-json.js
src/shared/copy-views.js

Fix faulty error path during shared file copying

---

src/actions/autoinstall/find-lambda-deps.js
test/mocks/deps-cjs/subfolder/subsubfolder/urls.js
test/mocks/deps-esm/subfolder/subsubfolder/urls.js
test/unit/src/actions/autoinstall/get-lambda-deps-tests.js

Fix false positive treeshaking of imports from http[s]

---

changelog.md
package.json
src/hydrate.js

Traverse folders that start with `.` looking for Lambda package files to hydrate

---

src/hydrate.js
test/integration/_shared.js

Fix lingering Windows issues with path normalization in Glob 8

---

changelog.md
src/actions/autoinstall/get-lambda-deps.js
src/actions/install-update.js
src/lib/index.js
src/shared/copy.js
test/integration/_shared.js

Handle obscure case where lingering broken symlinks would not be properly removed by the shared file copier

---

changelog.md
src/actions/autoinstall/get-root-deps.js

Fix issue where Hydrate would potentially install the wrong dependency version from dev deps

---

changelog.md
package.json
src/actions/autoinstall/find-lambda-deps.js
src/actions/autoinstall/get-lambda-deps.js
src/actions/autoinstall/get-shared-deps.js
src/actions/autoinstall/index.js
test/mocks/deps-cjs/one.js
test/mocks/deps-esm/one.js
test/unit/src/actions/autoinstall/get-lambda-deps-tests.js

`nodejs18.x` Lambda support

---

changelog.md
package.json
src/actions/autoinstall/index.js

Partially address #1405

---

changelog.md
src/actions/autoinstall/index.js
src/hydrate.js
src/shared/copy-plugins.js
src/shared/get-paths.js

Add additional multi-tenant Lambda checks

---

src/actions/autoinstall/index.js

Fixes architect/architect#1456.
Thanks again!

Add hydrate per function config option

---

changelog.md
src/actions/autoinstall/node/get-lambda-deps.js
src/actions/autoinstall/node/index.js

Add additional dependency ignoring property case

---

changelog.md
src/actions/autoinstall/index.js
src/actions/autoinstall/node/index.js

Fix issue where Hydrate fails on projects with only an ASAP root handler, no other Lambdas; fixes #1491

---

changelog.md
package.json
src/actions/install-update.js
test/unit/src/actions/install-update-tests.js

Path issue
